// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxysnxigsvuybqbjfxvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4eXNueGlnc3Z1eWJxYmpmeHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5Mzc5MDQsImV4cCI6MjA1NzUxMzkwNH0.TGe3ad7RoYWeRbZVyPSItHBcAQhTolqETjGd5jN2Ri8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);